# Generated by Django 5.2 on 2025-10-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_result_comparison_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='metrics_used',
        ),
        migrations.AddField(
            model_name='comparison',
            name='metrics_used',
            field=models.ManyToManyField(to='metrics.metric'),
        ),
    ]
